name: ci-ubuntu

on:
  push:
    branches:
      - 'master'
      - 'release/**'
  pull_request:
    branches:
      - 'master'

jobs:
  unit-test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-18.04
          - ubuntu-20.04
        os_name:
          - linux
          - linux-openresty

    runs-on: ${{ matrix.platform }}
    env:
      SERVER_NAME: ${{ matrix.os_name }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0
        with:
          submodules: recursive

      - name: Cache Docker
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: /var/lib/docker/image
          key: ${{ matrix.platform }}-${{ matrix.os_name }}-docker-images

      - name: System install basic env
        run: |
          sudo apt update && sudo apt install neofetch

      - name: System print info
        run: |
          neofetch --stdout

      - name: Install
        run: |
          cd ci && docker-compose up

#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
